- name: Install libseccomp2 v2.5
  apt:
    deb: http://ftp.fr.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_amd64.deb

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - build-essential
    - git

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli

- name: Make sure that docker was started
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
